name: 'Setup npm and Cache'
description: 'Install npm, setup npm cache, and install dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      run: npm ci
      shell: bash

    - name: Verify installation
      run: |
        node --version && npm --version && npm list --depth=0
      shell: bash
