name: 'Install Playwright Browser'
description: 'Installs the specified Playwright browser and its dependencies'

inputs:
  browser:
    description: 'Browser to install'
    required: true
    type: choice
    options:
      - chromium
      - firefox
      - webkit
      - chrome
      - edge
      - safari

runs:
  using: 'composite'
  steps:
    - name: Install browser and dependencies
      shell: bash
      run: |
        npx playwright install ${{ inputs.browser }}
        npx playwright install-deps
