name: 'Install Playwright Browser'
description: 'Installs the specified Playwright browser and its dependencies'

inputs:
  browser:
    description: 'Browser to install'
    required: true
    type: choice
    options:
      - chromium
      - firefox
      - webkit
      - chrome
      - msedge
      - safari

runs:
  using: 'composite'
  steps:
    - name: Cache Playwright browser
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ inputs.browser }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          playwright-${{ inputs.browser }}-${{ runner.os }}-

    - name: Install browser and dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npx playwright install ${{ inputs.browser }}
        npx playwright install-deps
