name: "Playwright Tests"
on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to run tests in"
        required: true
        default: "chromium"
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - chrome
          - edge
          - safari
      shards:
        description: "Number of shards to run"
        required: true
        default: "1"
      retries:
        description: "Number of retries for failed tests"
        required: true
        default: "0"
      workers:
        description: "Number of workers to run in parallel"
        required: true
        default: "1"

env:
  BASE_URL: "https://automationexercise.com"

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-focal
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node, npm and cache
        uses: './.github/actions/setup-npm'

      - name: Set environment variables
        run: |
          {
            echo "BROWSER=${{ github.event.inputs.browser }}"
            echo "SHARDS=${{ github.event.inputs.shards }}"
            echo "RETRIES=${{ github.event.inputs.retries }}"
            echo "WORKERS=${{ github.event.inputs.workers }}"
          } >> $GITHUB_ENV

      - name: Create test matrix
        id: create-matrix
        run: |
          echo "Creating matrix..."
          shards=${{ github.event.inputs.shards }}
          if [ -z "$shards" ]; then
            shards=1
          fi
          shardArray=$(seq -s, 1 $shards | sed 's/,/","/g')
          matrix=$(echo "{\"shard\": [\"$shardArray\"], \"total_shards\": [\"$shards\"]}")
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

      - name: Install Browsers
        uses: ./.github/actions/install-browser
        with:
          browser: ${{ github.event.inputs.browser }}

  run-tests:
    needs: setup-environment
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-focal
    strategy:
      matrix: ${{ fromJson(needs.setup-environment.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node, npm and cache
        uses: './.github/actions/setup-npm'

      - name: Install Browsers
        uses: ./.github/actions/install-browser
        with:
          browser: ${{ github.event.inputs.browser }}

      - name: Run Playwright tests
        run: |
          npx playwright test \
            --config=playwright/playwright.config.ts \
            --shard=${{ matrix.shard }}/${{ matrix.total_shards }} \
            --project=tests \
            --workers=${{ github.event.inputs.workers }} \
            --retries=${{ github.event.inputs.retries }} \
            --reporter=blob \
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shard }}
          path: blob-report/
          retention-days: 7

  merge-reports:
    needs: run-tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-focal
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node, npm and cache
        uses: './.github/actions/setup-npm'

      - name: Download all test reports
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-merged-report
          path: playwright-report
          retention-days: 7